{% set name = "libksba" %}
{% set version = "1.6.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.gnupg.org/ftp/gcrypt/{{ name }}/{{ name }}-{{ version }}.tar.bz2
  sha256: cf72510b8ebb4eb6693eef765749d83677a03c79291a311040a5bfd79baab763
  patches:
    # Use distributed header, not the one in the source
    - patches/0001-fix-include-statement.patch
    # Prevent make from building the tests during the conda build stage
    - patches/0002-remove-tests-from-build.patch

build:
  number: 0
  # libgpg-error is unavailable on s390x
  skip: true  # [win or s390x]
  run_exports:
    - {{ pin_subpackage('libksba', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - patch
  host:
    - libgpg-error

test:
  requires:
    - {{ compiler('c') }}
  source_files:
    - tests

about:
  home: https://www.gnupg.org/software/libksba/index.html
  summary: Libksba is a library to make the tasks of working with X.509 certificates
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  description: |
    Libksba is a library to make the tasks of working with X.509 certificates,
    CMS data and related objects more easy. It provides a highlevel interface to
    the implemented protocols and presents the data in a consistent way.

extra:
  recipe-maintainers:
    - mariusvniekerk
    - zklaus
