travis:
  secure:
    BINSTAR_TOKEN: Jje0CytwPDlAVQ/E6zKeNxm/zQfPOFxm2UzmZ/WGsWtzXpJYg0JckJVyVNM78Dgx8QwCr2PTolf3LXQvzY3FZwQ+Uk6AP51fjZuzKu5iBShh4Evm8FjuR1bZaJRPJKj/abyylL+VKVpIcb9/mYVExZBt8d2p6JZX9q/ge5vVFNT8CVT4UF1594R5vhnJjcyor1WEe0pLqbtQDgK9v4PO73FoE0NoHBlueYZ5+InFfdlyN5LvZ7sB/PJQrQRaANGKR/hA+nXBeHUOfHGDOoX2CdBOVuTY2pGdyfOf+87hmAs+zPfYKAWdLOSczy+0aMnPURs1hea7K3IBDvtr7KQV4AGLNADONDN3FzBUPyyxauxnKfTCZWZeRV5+/jSMlRlcvBvo2puGK8IYbDzHI44Me7UpJpIzRM1iSH5T95iCQLHgmFyt6ZosXQ5GAxDfqD/VwXZ70Zvh0QPcQcVdg2sU84M2XDPMrI084roMrVjfDxfWWfZGjWLiiGIz+xhiO9OYOLcWWH9flpbv7EH+URNV85LevayRT8ujKOYq0/G3L0OGy+3acRn/HkLbztI/BkOjFc5A585e2+vt/yHOcTiuPdokyPhUyHpb1pDDEdZsTgsovAYq+tN6Ho4wW1/Iai75f3bUzuIvEgNxNFZovbckoAuLcHOh+2HdZsvTubMWMpE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
