travis:
  secure:
    BINSTAR_TOKEN: YCGtYYWw6xZ4ZDHXX4Y61sOF6q09Um91vRpvU/dekeVITAC1KmVyGir9iel4nmOOYjYtUtlVUrzD5CDkhw6lfMj5c2h3dWmhZ+VUAGXDI4Rt5sII3SIdA/1b40TqXXFYzzLr5Q9gUroIJFr5MiXoxF+Jv50FHERxp9YE8Q2N7wthzB+uZhV6WxqjiykPmqbMbvdej9PyUsHcopaf+ftRHM+FND3ws7kt3uRNFmdOxlaf+RmKam9XWi+r8fYkh2UKQ7JQErSjOV6OxhmnIpqjl7zJTTESYHjEHfhXmthw4Neq5pANX9MfGw+QZdyLh12DuKvCCzBcBNOauToo5vdLPOaOdTJKPHFRB5BSxli2jjPluTYCRe8oLMC1hE+4Qsd4I3mSahdvzClZtIwqivQgVNaFK6G8dcdl+p09mpahbyzgWwu0arX7F68m8BJrYPNwk9knleu/KToQPWuGAWQgSXe1k1TT4fQJkcLDwIjDrg4p9j7BO+ghU3NqSH2gjNMRYVWdgU8j57Kc/Ndu1zTa0LxVkd7QK90w5b7Q25rxna8n69Tk4WubhbPtYNE9w0bWzG092Z/1VtuSyVW3jT94hCJe0Md5GB8ARfsnOLALhhphFL5oUUxUkKOqA7iDH4IoLmpq8+dI9WGAtNpKy7rKyadEKc3uVjvkzzSRW2wQdm0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
